### ISSUE TITLE
suggestion : repo name change ?

### ISSUE THREAD

**Issue by cyberboy666** [gaeljaton/Sync-Ope---analog-video-sync-stripper-injector-mixer#1]
just a suggestion that the repo title could be changed to "Sync-Ope" , while "analog-video-sync-stripper-injector-mixer" can be in the repo's subtitle.

usually github repos dont describe the project in the repo name, this is what the subtitle and readme is good for + makes it easier to share and remember the link . 😊

**Comment by gaeljaton** [comment]
yes, you're right!

**Comment by cyberboy666** [comment]
😅
